# -*- coding: utf-8 -*-
tweets = [
    {'type': 'text', 'text': u'Un chirlo no es violencia'},
    {'type': 'text', 'text': u'Are you watching closely?'},
    {'type': 'text', 'text': u'Una novia que me traiga Mc a la cama'},
    {'type': 'text', 'text': u'( •—• ) Tadashi is here'},
    {'type': 'image', 'text': u'Mi fantasia sexual', 'image': 'papas.jpg'},
    {'type': 'image', 'text': u'Hoy se sale fuerte', 'image': 'pachorra.jpg'},
    {'type': 'text', 'text': u'Necesito ropa negra'},
    {'type': 'text', 'text': u'OUR WORK IS NEVER OVER'},
    {'type': 'text', 'text': u'Not my fucking tempo'},
    {'type': 'text', 'text': u'Cuando me cierran el Mac en la cara https://vine.co/v/edzBEY1ajUa'},
    {'type': 'text', 'text': u'Every magic trick consists of three parts'},
    {'type': 'text', 'text': u'https://www.youtube.com/watch?v=uQ0ODCMC6xs'},
    {'type': 'text', 'text': u'Son un publico horrible'},
    {'type': 'image', 'text': u'Todo lo que esta mal en este mundo', 'image': 'animalprint.jpg'},
    {'type': 'text', 'text': u'No me preguntes, solo soy una chica, jiji'},
    {'type': 'text', 'text': u'Madurar? Eso es para las frutas'},
    {'type': 'image', 'image': 'noescape.gif'},
    {'type': 'text', 'text': u'Under my umbrella-ella-ella-eh eh eh eh eh https://www.youtube.com/watch?v=CvBfHwUxHIk'},
    {'type': 'text', 'text': u'Una novia que se vista bien'},
    {'type': 'text', 'text': u'ABAD ROMANCE'},
    {'type': 'text', 'text': u'.@abadbot era chiste y quedo'},
    {'type': 'text', 'text': u'¯\_(ツ)_/¯'},
    {'type': 'text', 'text': u'VIERNES! https://www.youtube.com/watch?v=qgKThrCj8OM'},
    {'type': 'text', 'text': u'Stay hungry, stay foolish'},
    {'type': 'text', 'text': u'Odio que solo se me peguen las canciones malas.'},
    {'type': 'text', 'text': u'Quiero vivir adentro de Burger Joint'},
    {'type': 'text', 'text': u'"I never look back, darling! It distracts from the now" - Edna Mode'},
    {'type': 'text', 'text': u'3:14 every night.'},
]
