tweets = [
    {'type': 'text', 'text': 'Un chirlo no es violencia'},
    {'type': 'text', 'text': 'Are you watching closely?'},
    {'type': 'text', 'text': 'Una novia que me traiga Mc a la cama'},
    {'type': 'text', 'text': '( •—• ) Tadashi is here'},
    {'type': 'image', 'text': 'Mi fantasia sexual', 'image': 'papas.jpg'},
    {'type': 'image', 'text': 'Hoy se sale fuerte', 'image': 'pachorra.jpg'},
    {'type': 'text', 'text': 'Necesito ropa negra'},
    {'type': 'text', 'text': 'XXXXX, que no había cerrado ese antro?'},
    {'type': 'text', 'text': 'OUR WORK IS NEVER OVER'},
    {'type': 'text', 'text': 'Not my fucking tempo'},
    {'type': 'text', 'text': 'Cuando me cierran el Mac en la cara https://vine.co/v/edzBEY1ajUa'},
    {'type': 'text', 'text': 'Every magic trick consists of three parts'},
    {'type': 'text', 'text': 'https://www.youtube.com/watch?v=uQ0ODCMC6xs'},
    {'type': 'text', 'text': 'Son un publico horrible'},
    {'type': 'image', 'text': 'Todo lo que esta mal en este mundo', 'image': 'animalprint.jpg'},
    {'type': 'text', 'text': 'No me preguntes, solo soy una chica, jiji'},
    {'type': 'text', 'text': 'Madurar? Eso es para las frutas'},
    {'type': 'image', 'image': 'noescape.gif'},
    {'type': 'text', 'text': 'Under my umbrella-ella-ella-eh eh eh eh eh https://www.youtube.com/watch?v=CvBfHwUxHIk'},
    {'type': 'text', 'text': 'Una novia que se vista bien'},
    {'type': 'text', 'text': 'ABAD ROMANCE'},
    # {'type': 'text', 'text': 'Era un chiste y quedo '},
    {'type': 'text', 'text': '¯\_(ツ)_/¯'},
]
